name: bankapp3
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  equatable: ^2.0.7
  http: ^1.4.0
  flutter_secure_storage: ^9.2.4
  internet_connection_checker: ^3.0.1
  bloc: ^9.0.0
  local_auth: ^2.3.0
  pointycastle: ^4.0.0
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  connectivity_plus: ^6.1.4
  asn1lib: ^1.6.4
  firebase_messaging: ^15.2.9
  sqflite: ^2.3.2
  path: ^1.9.0
  hive_flutter: ^1.1.0
  uuid: ^4.5.1
  firebase_core: ^3.15.2
  flutter_local_notifications: ^19.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icon/icon.png
